### ISSUE TITLE
is it broken with purescript 0.10?

### ISSUE THREAD

**Issue by bogus34** [purescript/purescript-maybe#23]
I got an error building empty project with installed purescript-maybe:

    in module Data.Maybe.First
    at /tmp/2/bower_components/purescript-maybe/src/Data/Maybe/First.purs line 40, column 1 - line 40, column 50

    No type class instance was found for
                                   
    Control.Monad.Monad (Maybe a)

**Comment by garyb** [comment]
No, it's not - this is one of the libraries that has been updated. What version are you depending on though? v2.0.0 is the latest.

**Comment by paf31** [comment]
Also what compiler version?

**Comment by garyb** [comment]
@paf31 beat me to it :smile: this might fail in 0.10.0 (which was pre-release), but not 0.10.1 I think?

**Comment by bogus34** [comment]
Yes you are indeed ridht! Works with 0.10.1
Thanks!
