### ISSUE TITLE
Build fails against prelude 2.4.0

### ISSUE THREAD

**Issue by aij** [purescript/purescript-maybe#28]
Looks like this now requires prelude 2.5.0.

This is the error:

```
ERROR in [1/1 UnknownImport] bower_components/purescript-maybe/src/Data/Maybe.purs:11:17
  
  11  import Data.Eq (class Eq1)
                      ^^^^^^^^^

  Cannot import type class Eq1 from module Data.Eq
  It either does not exist or the module does not export it.
```

**Comment by garyb** [comment]
Oops, yeah - I didn't bump the minimum bound high enough. :/

This should generally work though, since the `^` constraints means it will take the latest compatible version, which 2.5.0 is.

**Comment by aij** [comment]
Yeah, I imagine it would have worked if we didn't have other constraints on purescript-prelude.

**Comment by passy** [comment]
@garyb Could you tag a new release for this? :)

**Comment by garyb** [comment]
@passy it was already done! https://github.com/purescript/purescript-maybe/releases/tag/v2.1.1

**Comment by passy** [comment]
@garyb Woops, sorry. And thank you! :)
