### ISSUE TITLE
Why `Last a` is defined in terms of Maybe?

### ISSUE THREAD

**Issue by safareli** [purescript/purescript-maybe#34]
it can also be defined like this:

```purescript
instance semigroupLast :: Semigroup a => (Last a) where
  append _ last = last

instance monoidLast :: Monoid a => (Last a) where
  mempty = Last mempty
```

**Comment by garyb** [comment]
That gives you some pretty odd behaviour - the `Semigroup a` instance is unused, and it restricts the usage of `Last` to only work with types that are `Monoid`s.

The purpose of this `Last` is to take the last `Just` value, since there's no guarantee there is one it has to be defined as a wrapping of `Maybe`. The `Last` you're describing is just a different thing.

**Comment by garyb** [comment]
The `Last` you want is `Dual (Const a)` or something like that I think.

**Comment by garyb** [comment]
Ah not quite, the `Const` `Semigroup` isn't right for that.

**Comment by safareli** [comment]
yah no need for Semigroup:
```
type Last a = Last a
instance semigroupLast :: (Last a) where
  append _ last = last

instance monoidLast :: Monoid a => (Last a) where
  mempty = Last mempty
```

**Comment by garyb** [comment]
Yeah - it's still a different `Last` though, it has a different purpose than this one:

``` purescript
-- current:
fold [Last (Just 1), Last (Just 2), Last Nothing] = Last (Just 2)

-- yours (assuming there was also a `Semigroup Int`, as without that there's no `Monoid Int`):
fold [Last (Just 1), Last (Just 2), Last Nothing] = Last Nothing
```

**Comment by safareli** [comment]
Yah this has different behaviour. where do you think is the place for such Last First (if is any:d)?

**Comment by garyb** [comment]
`Data.Monoid.Left` and `Data.Monoid.Right` perhaps? I'm not sure really :smile:

**Comment by safareli** [comment]
Monod instance is not lawful so we can just remove it and we will be left with Semigroup.
So maybe `Data.Semigroup.{Left,Right}`?

**Comment by matthewleon** [comment]
Just found this... I've made an issue for it on prelude here: https://github.com/purescript/purescript-prelude/issues/157

Though perhaps the separate repo approach is best: https://github.com/matthewleon/purescript-semigroups

**Comment by matthewleon** [comment]
> Yeah - it's still a different Last though, it has a different purpose than this one:

```purescript
fold [Just (Last 1), Just (Last 2), Nothing] = Just (Last 2)
```

Should yield what you want, no? It seems to me that you can achieve the same effects using the `purescript-semigroups` `First`/`Last` as with the `purescript-maybe` versions.

**Comment by matthewleon** [comment]
I made a post here, but it was wrong. Deleted my dumb idea.

**Comment by hdgarrood** [comment]
Semigroup `First`/`Last` are now in the Prelude: https://github.com/purescript/purescript-prelude/issues/157 so I think this can be closed.

**Comment by garyb** [comment]
There is the question around this still: https://github.com/purescript/purescript-newtype/issues/16 as we won't need the `First` / `Last` defined in here with that combinator, since it can use the semigroup version instead.

**Comment by hdgarrood** [comment]
Ah of course. Do you think this issue should be reopened, then?

**Comment by garyb** [comment]
Not necessarily, just wanted the cross link between here and the other issue as a reminder to maybe delete these if we decide the other thing is good to have.
